### ISSUE TITLE
Fail to parse ical file in using ics python library

### ISSUE THREAD

**Issue by calixteman** [mozilla-necko/triage-list#2]
With:
```python
from ics import Calendar

with open('necko-triage.ics', 'r') as In:
    c = Calendar(In.read())
print(c)
```
I get the error:
```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    c = Calendar(In.read())
  File "/usr/local/lib/python3.7/dist-packages/ics/icalendar.py", line 69, in __init__
    self._populate(container[0])  # Use first calendar
  File "/usr/local/lib/python3.7/dist-packages/ics/component.py", line 60, in _populate
    extractor.function(self, lines)  # Send a list or empty list
  File "/usr/local/lib/python3.7/dist-packages/ics/icalendar.py", line 202, in timezone
    timezones = tzical(fake_file)  # tzical does not like strings
  File "/usr/local/lib/python3.7/dist-packages/dateutil/tz/tz.py", line 1273, in __init__
    self._parse_rfc(fobj.read())
  File "/usr/local/lib/python3.7/dist-packages/dateutil/tz/tz.py", line 1375, in _parse_rfc
    "at least one component is needed")
ValueError: at least one component is needed
```
The vtimezone entry should contain some components (https://tools.ietf.org/html/rfc5545#section-3.6.5)
The issue can be fixed in specifying timezone in triage.js:
```javascript
builder.timezone = "Europe/Dublin";
builder.tzid = "Europe/Dublin";
```
and the generated ics can now be parsed.

**Comment by mayhemer** [comment]
Looks like there is a 3 years old pending push request for UTF zone support:
https://github.com/kushal-likhi/node-ical-toolkit/pull/8

Note that Etc/GMT (http://unicode.org/cldr/charts/latest/supplemental/zone_tzid.html) is not specified in the list of supported zones in ical-toolkit.

Not sure why Dublin and not London, but let's do it, the events are all-day anyway.

**Comment by calixteman** [comment]
I tried Etc/GMT too. 
And if you prefer London or anything else, it's up to you ;)
